spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tietokantaratkaisut_pop_schema
    username: dbuser
    password: jipijipijipijipi

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  application:
    name: demo
